### PR TITLE
initial commit of the SSD103 OLED displays

### PR DESCRIPTION
**Pull request by rakyll**
/cc @mattetti and @zankich. Please review the design.

### CODE REVIEW

**Comment by mattetti** [comment]
I think it would be worth spending a bit of time agreeing on a common & consistent OLED/display API. We have another OLED device: https://github.com/goiot/devices/blob/master/grove/oled96x96/oled96x96.go and some LCDs. Maybe we can agree on naming for methods like scrolling, rendering and moving of cursor. I don't have a particular preference. I would just want consistency.

**Comment by rakyll** [comment]
Abstracting all OLED displays could be depending on the variety of features supported but consistent naming would be awesome to have.

**Comment by mattetti** [comment]
I agree, it's all about consistent naming not enforced interface.

**Comment by rakyll** [comment]
Also note that I renamed some methods to be consistent with oled96x96 before you merge this PR. It looks more they are both coming from the same author.

**Pull request merged**
